.NH 1
Performances

.NH 2
newtype, type and data
.LP
.TBD

.NH 2
Laziness
.LP
Laziness
.BULLET
can make qualitative improvements to performance
.br
.BULLET
can hurt performance in some cases.
.br
It implies to keep track of what should or shouldn't be executed.
.BULLET
Makes code simpler.
.BULLET
Makes hard problems conceivable
.BULLET
Allows for separation of concerns with regard to generating and processing data.
