.SECTION Assembly
Assembly language is the human form of what is exactly performed by the hardware.
The langugae is driven by the hardware and all its particularities in term of memory management.
What isn't coded in assembly is (most likely) hardwired, mechanical, electronic.

Several tools allow to transcript assembly code into executable format, allowing (slightly) different assembly code (different syntaxes to represent the same stuff).

