.so haskelltut/macros.ms
.so haskelltut/header.ms
.2C
.so haskelltut/intro.ms
.so haskelltut/base.ms
.so haskelltut/usual-type-classes.ms
.so haskelltut/useful-functions.ms
.so haskelltut/complex-data-structures.ms
.so haskelltut/lenses.ms
.so haskelltut/networking.ms
.so haskelltut/profiling.ms
.so haskelltut/performances.ms
.so haskelltut/parallelism.ms
.so haskelltut/stuff.ms
.so haskelltut/misc.ms
.so haskelltut/annex_type-classes.ms
.so haskelltut/annex_vocabulary.ms
